// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ActorDefinition {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTORDEFINITION
public:
    class ActorDefinition& operator=(class ActorDefinition const &) = delete;
    ActorDefinition(class ActorDefinition const &) = delete;
    ActorDefinition() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ACTORDEFINITION
#endif
    MCAPI ActorDefinition(std::string const &);
    MCAPI void parse(class Json::Value, class ActorDefinitionDescriptor &, class ActorFactory &, class SemVersion);
    MCAPI void parseAttributes(class Json::Value &, class ActorDefinitionDescriptor &);
    MCAPI void parseEntityDescription(class Json::Value &);
    MCAPI void parseEvents(class Json::Value const &);
    MCAPI ~ActorDefinition();

};