// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ActorSkeletalAnimation {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ACTORSKELETALANIMATION
public:
    class ActorSkeletalAnimation& operator=(class ActorSkeletalAnimation const &) = delete;
    ActorSkeletalAnimation(class ActorSkeletalAnimation const &) = delete;
    ActorSkeletalAnimation() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ACTORSKELETALANIMATION
#endif
    MCAPI ActorSkeletalAnimation(std::string const &, bool, std::string const &);
    MCAPI class ActorAnimationEvent & addActorEvent(float, std::string const &, enum CurrentCmdVersion);
    MCAPI class ActorParticleEffectEvent & addParticleEffectEvent(float);
    MCAPI class ActorSoundEffectEvent & addSoundEffectEvent(float);
    MCAPI void initPrecomputedInterpolation();
    MCAPI ~ActorSkeletalAnimation();

};