// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace AutomaticFeatureRules {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI void parseAutomaticFeatures(class ResourcePackManager &, class IWorldRegistriesProvider &, bool, std::vector<struct AutomaticFeatureRules::AutomaticFeatureRule> (&)[7]);

};