// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct BoostItem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_BOOSTITEM
public:
    struct BoostItem& operator=(struct BoostItem const &) = delete;
    BoostItem(struct BoostItem const &) = delete;
    BoostItem() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_BOOSTITEM
#endif
    MCAPI void setItem(std::string const &);
    MCAPI void setReplacement(std::string const &);

};