// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "AuxDataBlockItem.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ChemistryAuxDataBlockItem : public AuxDataBlockItem {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_CHEMISTRYAUXDATABLOCKITEM
public:
    class ChemistryAuxDataBlockItem& operator=(class ChemistryAuxDataBlockItem const &) = delete;
    ChemistryAuxDataBlockItem(class ChemistryAuxDataBlockItem const &) = delete;
    ChemistryAuxDataBlockItem() = delete;
#endif

public:
    /*0*/ virtual ~ChemistryAuxDataBlockItem();
    /*5*/ virtual void __unk_vfn_5();
    /*26*/ virtual void __unk_vfn_26();
    /*27*/ virtual void __unk_vfn_27();
    /*31*/ virtual void __unk_vfn_31();
    /*32*/ virtual void __unk_vfn_32();
    /*34*/ virtual void __unk_vfn_34();
    /*37*/ virtual void __unk_vfn_37();
    /*43*/ virtual void __unk_vfn_43();
    /*46*/ virtual void __unk_vfn_46();
    /*47*/ virtual void __unk_vfn_47();
    /*49*/ virtual void __unk_vfn_49();
    /*50*/ virtual void __unk_vfn_50();
    /*75*/ virtual void fixupOnLoad(class ItemStackBase &) const;
    /*79*/ virtual void __unk_vfn_79();
    /*80*/ virtual void __unk_vfn_80();
    /*90*/ virtual void __unk_vfn_90();
    /*97*/ virtual void __unk_vfn_97();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_CHEMISTRYAUXDATABLOCKITEM
#endif

};