// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "Json.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class DefinitionEventLoader {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_DEFINITIONEVENTLOADER
public:
    class DefinitionEventLoader& operator=(class DefinitionEventLoader const &) = delete;
    DefinitionEventLoader(class DefinitionEventLoader const &) = delete;
    DefinitionEventLoader() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_DEFINITIONEVENTLOADER
#endif
    MCAPI static class DefinitionEvent loadEvent(class Json::Value);

//private:
    MCAPI static class DefinitionEvent loadCollection(class Json::Value);

private:

};