// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class DefinitionEvent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_DEFINITIONEVENT
#endif
    MCAPI DefinitionEvent(class DefinitionEvent &&);
    MCAPI DefinitionEvent(class DefinitionEvent const &);
    MCAPI DefinitionEvent();
    MCAPI void evaluateGroups(class Actor &, std::vector<struct DefinitionModifier> &, class VariantParameterList const &);
    MCAPI class DefinitionEvent & operator=(class DefinitionEvent &&);
    MCAPI class DefinitionEvent & operator=(class DefinitionEvent const &);
    MCAPI ~DefinitionEvent();

};