// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace DyeColorUtil {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI int getAuxValue(enum ItemColor);
    MCAPI enum ItemColor getItemColor(int);

};