// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class EntitySensorComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ENTITYSENSORCOMPONENT
public:
    class EntitySensorComponent& operator=(class EntitySensorComponent const &) = delete;
    EntitySensorComponent(class EntitySensorComponent const &) = delete;
    EntitySensorComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ENTITYSENSORCOMPONENT
#endif
    MCAPI EntitySensorComponent(class EntitySensorComponent &&);
    MCAPI ~EntitySensorComponent();

//private:

private:
    MCAPI static int const NO_MAX_COUNT;

};