// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct IsExperimentalDescription {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ISEXPERIMENTALDESCRIPTION
public:
    struct IsExperimentalDescription& operator=(struct IsExperimentalDescription const &) = delete;
    IsExperimentalDescription(struct IsExperimentalDescription const &) = delete;
    IsExperimentalDescription() = delete;
#endif
public:
    /*0*/ virtual ~IsExperimentalDescription();
    /*1*/ virtual char const * getJsonName() const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ISEXPERIMENTALDESCRIPTION
#endif

};