// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ItemDescriptorCount {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_ITEMDESCRIPTORCOUNT
public:
    ItemDescriptorCount() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_ITEMDESCRIPTORCOUNT
#endif
    MCAPI ItemDescriptorCount(class ItemDescriptorCount const &);
    MCAPI ItemDescriptorCount(class Block const &, unsigned short);
    MCAPI ItemDescriptorCount(class Item const &, int, unsigned short);
    MCAPI class ItemDescriptorCount & operator=(class ItemDescriptorCount const &);

};