// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace LevelDataKeys {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI extern class StringKey EDUCATION_OID;
    MCAPI extern class StringKey GAME_TYPE;
    MCAPI extern class StringKey GENERATOR;
    MCAPI extern class StringKey LIMITED_WORLD_DEPTH;
    MCAPI extern class StringKey LIMITED_WORLD_WIDTH;
    MCAPI extern class StringKey LOADED_PLAYER_TAG;
    MCAPI extern class StringKey SEED;
    MCAPI extern class StringKey SPAWN_POS;

};