// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "TreeHelper.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MegaPineTreeCanopy {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MEGAPINETREECANOPY
public:
    class MegaPineTreeCanopy& operator=(class MegaPineTreeCanopy const &) = delete;
    MegaPineTreeCanopy(class MegaPineTreeCanopy const &) = delete;
    MegaPineTreeCanopy() = delete;
#endif

public:
    /*0*/ virtual ~MegaPineTreeCanopy();
    /*1*/ virtual class std::optional<class BlockPos> placeCanopy(class IBlockPlacementTarget &, class BlockPos const &, class Random &, struct TreeHelper::TreeParams const &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MEGAPINETREECANOPY
#endif

};