// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct MolangArrayVariable {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MOLANGARRAYVARIABLE
public:
    struct MolangArrayVariable& operator=(struct MolangArrayVariable const &) = delete;
    MolangArrayVariable(struct MolangArrayVariable const &) = delete;
    MolangArrayVariable() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MOLANGARRAYVARIABLE
#endif
    MCAPI ~MolangArrayVariable();
    MCAPI static struct MolangArrayVariable defaultErrorValue;

};