// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct MolangGenericQueryFunctionPtr {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MOLANGGENERICQUERYFUNCTIONPTR
public:
    struct MolangGenericQueryFunctionPtr& operator=(struct MolangGenericQueryFunctionPtr const &) = delete;
    MolangGenericQueryFunctionPtr(struct MolangGenericQueryFunctionPtr const &) = delete;
    MolangGenericQueryFunctionPtr() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MOLANGGENERICQUERYFUNCTIONPTR
#endif
    MCAPI ~MolangGenericQueryFunctionPtr();
    MCAPI static struct MolangGenericQueryFunctionPtr defaultErrorValue;

};