// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

struct MolangScriptArg {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MOLANGSCRIPTARG
public:
    MolangScriptArg() = delete;
#endif
public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MOLANGSCRIPTARG
#endif
    MCAPI MolangScriptArg(struct MolangScriptArg const &);
    MCAPI MolangScriptArg(float);
    MCAPI struct MolangScriptArg & operator=(struct MolangScriptArg const &);
    MCAPI ~MolangScriptArg();

};