// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class MoveControlComponent {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_MOVECONTROLCOMPONENT
public:
    class MoveControlComponent& operator=(class MoveControlComponent const &) = delete;
    MoveControlComponent(class MoveControlComponent const &) = delete;
    MoveControlComponent() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_MOVECONTROLCOMPONENT
#endif
    MCAPI void initializeFromDefinition(class Mob &, struct MoveControlDescription *);
    MCAPI void setInternalType(std::unique_ptr<class MoveControl>);

};