// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "StructureFeature.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class OceanMonumentFeature : public StructureFeature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_OCEANMONUMENTFEATURE
public:
    class OceanMonumentFeature& operator=(class OceanMonumentFeature const &) = delete;
    OceanMonumentFeature(class OceanMonumentFeature const &) = delete;
    OceanMonumentFeature() = delete;
#endif

public:
    /*0*/ virtual ~OceanMonumentFeature();
    /*1*/ virtual void initMobSpawnTypes(class HardcodedSpawnAreaRegistry &);
    /*3*/ virtual bool getNearestGeneratedFeature(class Dimension &, class BiomeSource &, class BlockPos const &, class BlockPos &);
    /*4*/ virtual bool isFeatureChunk(class BiomeSource const &, class Random &, class ChunkPos const &, unsigned int);
    /*5*/ virtual std::unique_ptr<class StructureStart> createStructureStart(class Dimension &, class BiomeSource &, class Random &, class ChunkPos const &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_OCEANMONUMENTFEATURE
#endif
    MCAPI OceanMonumentFeature(unsigned int);

};