// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class RecipeIngredient {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RECIPEINGREDIENT
public:
    class RecipeIngredient& operator=(class RecipeIngredient const &) = delete;
    RecipeIngredient() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RECIPEINGREDIENT
#endif
    MCAPI RecipeIngredient(class RecipeIngredient const &);
    MCAPI RecipeIngredient(class Block const &, unsigned short);
    MCAPI RecipeIngredient(class Item const &, int, unsigned short);
    MCAPI ~RecipeIngredient();
    MCAPI static class RecipeIngredient EMPTY_INGREDIENT;

};