// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class RegionHillsLayer {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_REGIONHILLSLAYER
public:
    class RegionHillsLayer& operator=(class RegionHillsLayer const &) = delete;
    RegionHillsLayer(class RegionHillsLayer const &) = delete;
    RegionHillsLayer() = delete;
#endif

public:
    /*0*/ virtual ~RegionHillsLayer();
    /*1*/ virtual void init(__int64);
    /*2*/ virtual class LayerDetails::TransferData<class Biome *> _allocateAndFill(unsigned __int64, int, int, unsigned int, unsigned int) const;
    /*3*/ virtual void _fillArea(class LayerDetails::WorkingData<class Biome *, class Biome *> &, int, int, int, int, int) const;
    /*4*/ virtual class std::tuple<int, int, unsigned int, unsigned int> _getAreaRead(int, int, unsigned int, unsigned int) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_REGIONHILLSLAYER
#endif

};