// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "Json.hpp"
#include "Core.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ResourceLocation {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RESOURCELOCATION
public:
    class ResourceLocation& operator=(class ResourceLocation const &) = delete;
    ResourceLocation(class ResourceLocation const &) = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RESOURCELOCATION
#endif
    MCAPI ResourceLocation();
    MCAPI class Core::PathBuffer<std::string> getFullPath() const;
    MCAPI class ResourceLocation & operator=(class ResourceLocation &&);
    MCAPI bool operator==(class ResourceLocation const &) const;
    MCAPI void serialize(class Json::Value &) const;
    MCAPI ~ResourceLocation();

//private:
    MCAPI void _computeHashes();

private:

};