// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class Seasons {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SEASONS
public:
    class Seasons& operator=(class Seasons const &) = delete;
    Seasons(class Seasons const &) = delete;
    Seasons() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SEASONS
#endif
    MCAPI void postProcess(class LevelChunk &, class BlockSource &, class ChunkPos const &);

};