// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "Packet.hpp"

#define BEFORE_EXTRA

enum ScorePacketType {
    Change = 0x0,
    Remove_2 = 0x1,
};
#undef BEFORE_EXTRA

class SetScorePacket : public Packet {

#define AFTER_EXTRA
public:
    ScorePacketType mType;
    std::vector<ScorePacketInfo> mScoreInfo;
#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SETSCOREPACKET
public:
    class SetScorePacket& operator=(class SetScorePacket const &) = delete;
    SetScorePacket(class SetScorePacket const &) = delete;
    SetScorePacket() = delete;
#endif

public:
    /*0*/ virtual ~SetScorePacket();
    /*1*/ virtual enum MinecraftPacketIds getId() const;
    /*2*/ virtual std::string getName() const;
    /*3*/ virtual void write(class BinaryStream &) const;
    /*4*/ virtual enum StreamReadResult read(class ReadOnlyBinaryStream &);
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SETSCOREPACKET
#endif

//private:
    MCAPI SetScorePacket(enum ScorePacketType, struct ScoreboardId const &, class Objective const &);

private:

};