// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class StringKey {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_STRINGKEY
public:
    class StringKey& operator=(class StringKey const &) = delete;
    StringKey(class StringKey const &) = delete;
    StringKey() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_STRINGKEY
#endif
    MCAPI ~StringKey();

};