// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "Feature.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class TallGrassFeature : public Feature {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_TALLGRASSFEATURE
public:
    class TallGrassFeature& operator=(class TallGrassFeature const &) = delete;
    TallGrassFeature(class TallGrassFeature const &) = delete;
    TallGrassFeature() = delete;
#endif

public:
    /*0*/ virtual ~TallGrassFeature();
    /*1*/ virtual bool place(class BlockSource &, class BlockPos const &, class Random &) const;
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_TALLGRASSFEATURE
#endif
    MCAPI bool place(class BlockSource &, class BlockPos const &, class Random &, int, int) const;

};