// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace TreeHelper {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI class std::optional<class BlockPos> placeDecoratedBlock(class IBlockPlacementTarget &, class BlockPos const &, class Random &, class Block const &, struct TreeHelper::AttachableDecoration const &, struct TreeHelper::AttachableDecoration::DirectionMask const &);
    MCAPI class std::optional<class BlockPos> placeRadialBlockGroup(class IBlockPlacementTarget &, class BlockPos const &, class Random &, class Block const &, int, int, bool, std::vector<class Block const *> const &);
    MCAPI bool prepareSpawn(class IBlockPlacementTarget &, class BlockPos const &, int, std::vector<class Block const *> const &, std::vector<class Block const *> const &);

};