// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

namespace VanillaWorldSystems {

#define AFTER_EXTRA

#undef AFTER_EXTRA
    MCAPI class std::shared_ptr<class VanillaWorldSystems::Impl> init(class Level *, class ResourcePackManager *, class BlockDefinitionGroup *);

};