// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "llapi/Global.h"
#include "Actor.hpp"
#include "Animal.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class Wolf : public Animal {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_WOLF
public:
    class Wolf& operator=(class Wolf const &) = delete;
    Wolf(class Wolf const &) = delete;
    Wolf() = delete;
#endif

public:
    /*7*/ virtual ~Wolf();
    /*30*/ virtual void __unk_vfn_30();
    /*39*/ virtual void normalTick();
    /*45*/ virtual void addRider(class Actor &);
    /*54*/ virtual void __unk_vfn_54();
    /*61*/ virtual void __unk_vfn_61();
    /*76*/ virtual void __unk_vfn_76();
    /*81*/ virtual void __unk_vfn_81();
    /*88*/ virtual void __unk_vfn_88();
    /*90*/ virtual void __unk_vfn_90();
    /*98*/ virtual void __unk_vfn_98();
    /*100*/ virtual void __unk_vfn_100();
    /*110*/ virtual void setSitting(bool);
    /*121*/ virtual void __unk_vfn_121();
    /*132*/ virtual void handleEntityEvent(enum ActorEvent, int);
    /*157*/ virtual bool load(class CompoundTag const &, class DataLoadHelper &);
    /*169*/ virtual void __unk_vfn_169();
    /*177*/ virtual void onSynchedDataUpdate(int);
    /*182*/ virtual void __unk_vfn_182();
    /*206*/ virtual void __unk_vfn_206();
    /*207*/ virtual void __unk_vfn_207();
    /*228*/ virtual void __unk_vfn_228();
    /*231*/ virtual void __unk_vfn_231();
    /*238*/ virtual void __unk_vfn_238();
    /*240*/ virtual bool _hurt(class ActorDamageSource const &, int, bool, bool);
    /*246*/ virtual void __unk_vfn_246();
    /*257*/ virtual void __unk_vfn_257();
    /*265*/ virtual enum LevelSoundEvent getAmbientSound();
    /*290*/ virtual void __unk_vfn_290();
    /*298*/ virtual bool isAlliedTo(class Mob *);
    /*299*/ virtual bool doHurtTarget(class Actor *);
    /*300*/ virtual void __unk_vfn_300();
    /*325*/ virtual void onBorn(class Actor &, class Actor &);
    /*332*/ virtual void __unk_vfn_332();
    /*339*/ virtual void newServerAiStep();
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_WOLF
#endif

//private:
    MCAPI void _avoidSnowBury();
    MCAPI void _updateTintColor();

private:

};