// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class AABB {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_AABB
public:
    class AABB& operator=(class AABB const &) = delete;
    AABB(class AABB const &) = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_AABB
#endif
    MCAPI AABB();
    MCAPI AABB(float, float, float, float, float, float);
    MCAPI AABB(class Vec3 const &, class Vec3 const &);
    MCAPI class HitResult clip(class Vec3 const &, class Vec3 const &) const;
    MCAPI class Vec3 clipCollide(class AABB const &, class Vec3 const &, bool, float *) const;
    MCAPI bool contains(class Vec3 const &) const;
    MCAPI float distanceTo(class Vec3 const &) const;
    MCAPI float distanceToSqr(class AABB const &) const;
    MCAPI class AABB expanded(class Vec3 const &) const;
    MCAPI class AABB flooredCeiledCopy() const;
    MCAPI class AABB flooredCopy(float, float) const;
    MCAPI class AABB grow(class Vec3 const &) const;
    MCAPI bool intersects(class AABB const &) const;
    MCAPI bool intersects(class Vec3 const &, class Vec3 const &) const;
    MCAPI class AABB merge(class AABB const &) const;
    MCAPI class AABB & set(class Vec3 const &, class Vec3 const &);
    MCAPI void set(float, float, float, float, float, float);
    MCAPI class AABB shrink(class Vec3 const &) const;
    MCAPI static class AABB const EMPTY;

};