// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class CommandSelectorBase {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_COMMANDSELECTORBASE
public:
    class CommandSelectorBase& operator=(class CommandSelectorBase const &) = delete;
    CommandSelectorBase(class CommandSelectorBase const &) = delete;
    CommandSelectorBase() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_COMMANDSELECTORBASE
#endif
    MCAPI void addFilter(class std::function<bool (class CommandOrigin const &, class Actor const &)>);
    MCAPI void addTypeFilter(struct InvertableFilter<std::string> const &);
    MCAPI bool compile(class CommandOrigin const &, std::string &);
    MCAPI void setBox(class BlockPos);
    MCAPI void setPosition(class CommandPosition const &);
    MCAPI void setRadiusMax(float);
    MCAPI void setRadiusMin(float);
    MCAPI ~CommandSelectorBase();

//protected:
    MCAPI CommandSelectorBase(bool);
    MCAPI class std::shared_ptr<std::vector<class Actor *>> newResults(class CommandOrigin const &) const;

//private:
    MCAPI bool filter(class CommandOrigin const &, class Actor &, float) const;
    MCAPI bool matchName(class Actor const &) const;
    MCAPI bool matchTag(class Actor const &) const;
    MCAPI bool matchType(class Actor const &) const;

protected:

private:

};