// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class NetworkIdentifier {

#define AFTER_EXTRA
// Add Member There
    char filler[160];
public:
    LIAPI std::string getIP();

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_NETWORKIDENTIFIER
public:
    class NetworkIdentifier& operator=(class NetworkIdentifier const &) = delete;
    NetworkIdentifier(class NetworkIdentifier const &) = delete;
    NetworkIdentifier() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_NETWORKIDENTIFIER
#endif
    MCAPI std::string getAddress() const;
    MCAPI unsigned __int64 getHash() const;
    MCAPI bool isUnassigned() const;
    MCAPI bool operator==(class NetworkIdentifier const &) const;
    MCAPI std::string toString() const;

};