// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"
#include "Core.hpp"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class ResourcePack {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_RESOURCEPACK
public:
    class ResourcePack& operator=(class ResourcePack const &) = delete;
    ResourcePack(class ResourcePack const &) = delete;
    ResourcePack() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_RESOURCEPACK
#endif
    MCAPI ResourcePack(class Pack &);
    MCAPI bool areKnownFilesValid();
    MCAPI void forEachIn(class Core::Path const &, class std::function<void (class Core::Path const &)>, int, bool) const;
    MCAPI void generateAssetSet();
    MCAPI bool getResource(class Core::Path const &, std::string &, int) const;
    MCAPI bool hasResource(class Core::Path const &, int) const;
    MCAPI void setLocale(std::string const &);
    MCAPI ~ResourcePack();
    MCAPI static class Core::PathBuffer<std::string> const RESOURCE_PACK_BUG_ICON_PATH;
    MCAPI static class Core::PathBuffer<std::string> const RESOURCE_PACK_ICON_PATH;
    MCAPI static class Core::PathBuffer<std::string> const TEXTURES_LIST_PATH;

//private:
    MCAPI void _createSubpack(struct SubpackInfo const &);
    MCAPI void _createSubpacks();

private:

};