// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA
// Include Headers or Declare Types Here
// TODO: Need to verify
enum Mirror : unsigned char {
    None_15=0,
    X,
    Z,
    XZ,
};
enum Rotation : unsigned char {
    None_14=0,
    Rotate90,
    Rotate180,
    Rotate270,
    Total,
};

#undef BEFORE_EXTRA

class StructureSettings {

#define AFTER_EXTRA
// Add Member There
private:
char filler[104];

// public:
// inline StructureSettings(BlockPos const& size, bool ignoreEntities, bool ignoreBlocks)
//     : StructureSettings()
// {
//     setIgnoreBlocks(ignoreBlocks);
//     setIgnoreEntities(ignoreEntities);
//     setStructureSize(size);
// };

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_STRUCTURESETTINGS
public:
    class StructureSettings& operator=(class StructureSettings const &) = delete;
    StructureSettings(class StructureSettings const &) = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_STRUCTURESETTINGS
#endif
    MCAPI StructureSettings();
    MCAPI class StructureSettings & operator=(class StructureSettings &&);
    MCAPI ~StructureSettings();
    MCAPI static class BlockPos const DEFAULT_STRUCTURE_OFFSET;
    MCAPI static class BlockPos const DEFAULT_STRUCTURE_SIZE;

};