// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "../Global.h"

#define BEFORE_EXTRA

#undef BEFORE_EXTRA

class SynchedActorData {

#define AFTER_EXTRA

#undef AFTER_EXTRA
#ifndef DISABLE_CONSTRUCTOR_PREVENTION_SYNCHEDACTORDATA
public:
    class SynchedActorData& operator=(class SynchedActorData const &) = delete;
    SynchedActorData(class SynchedActorData const &) = delete;
    SynchedActorData() = delete;
#endif

public:
#ifdef ENABLE_VIRTUAL_FAKESYMBOL_SYNCHEDACTORDATA
#endif
    MCAPI class CompoundTag const & getCompoundTag(unsigned short) const;
    MCAPI float getFloat(unsigned short) const;
    MCAPI signed char getInt8(unsigned short) const;
    MCAPI std::string const & getString(unsigned short) const;
    MCAPI std::vector<std::unique_ptr<class DataItem>> packAll() const;
    MCAPI std::vector<std::unique_ptr<class DataItem>> packDirty();
    MCAPI ~SynchedActorData();

//private:
    MCAPI void _resizeToContain(unsigned short);

private:

};